# -*- coding: utf-8 -*-
"""Assignment8-CS-202151120.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DfKI5J5okTXWjXEKylQuMoajwgpC9IjR
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

filepath="/content/drive/MyDrive/DAV/weight-height.csv"

df=pd.read_csv(filepath)

height_data = df['Height']

def bootstrap(df, num_of_iterations, replacement=True):
    return [np.mean(np.random.choice(df, size=len(df), replace=replacement)) for _ in range(num_of_iterations)]

p = 10000 #Sample number of Bootstrap

r = 10000 #Sample number of CLT

l = 30  #sample size

# Perform CLT verification (with replacement=False)

q = [np.mean(np.random.choice(height_data, size=l, replace=False)) for _ in range(r)]

bootstrap_means = bootstrap(height_data, p)

# Calculate 95% Confidence Interval
confidence_interval = np.percentile(bootstrap_means, [2.5, 97.5])

plt.figure(figsize=(10, 10))

# CLT Verification
plt.subplot(1, 2, 1)
plt.hist(q, bins=30, density=True, alpha=0.6, color='g')
plt.title('Distribution of Sample Means (CLT)')
plt.xlabel('Height')
plt.ylabel('Density')

plt.subplot(1, 2, 2)
plt.hist(bootstrap_means, bins=30, density=True, alpha=0.6, color='b')
plt.title('Bootstrap Sampling Distribution')
plt.xlabel('Height')
plt.ylabel('Density')

plt.axvline(x=confidence_interval[0], color='red', linestyle='--', label='95% CI')
plt.axvline(x=confidence_interval[1], color='red', linestyle='--')

plt.legend()
plt.tight_layout()
plt.show()

print("95% Confidence Interval:", confidence_interval)